### ISSUE TITLE
Таблица отчет за период, выводить сумму итого

### ISSUE THREAD

**Issue by AcumenDev** [AcumenDev/EffectiveInterest#32]

**Comment by AcumenDev** [comment]
Нашел багу
![screenshot from 2017-05-04 14-10-53](https://cloud.githubusercontent.com/assets/675860/25701237/337bf61c-30d4-11e7-992c-d4eb1c3570f9.png)

**Comment by leonovdmitry** [comment]
теперь все вводимые float значения суммы будут правильно записываться(вместо разделителя , будет . ), пока для подсчета суммы добавил костыль с таким же преобразованием при подсчете суммы, похорошему нужно сконвертировать уже имеющиеся у пользователей данные в правильный формат, например выполнив экспорт импорт, и выпилить костыль. Можно также усложнить парсинг, добавить защиту от "дурака" чтобы не вводились буквы и символы, надо ли?

**Comment by AcumenDev** [comment]
Надо при вводе валидировать чтобы в бд хлам не ложить и с ним потом не воевать)

**Comment by AcumenDev** [comment]
![screenshot from 2017-05-09 18-44-27](https://cloud.githubusercontent.com/assets/675860/25859552/99229aea-34e7-11e7-9213-1c63c4f3a830.png)

**Comment by AcumenDev** [comment]
Надо глянуть почему суммы не сходяться и ограничить до 2х знаков

**Comment by leonovdmitry** [comment]
в последнем хз почему такая разница у меня расхождений не выходило, нужно на тех данных проверять, ограничение сделаю.
